### ISSUE TITLE
SCOPES vs SCOPE (index.js vs README.md)

### ISSUE THREAD

**Issue by rhbecker** [UWIT-IAM/oidc-client-nodejs#1]
[Line 23 of index.js](https://github.com/UWIT-IAM/oidc-client-nodejs/blob/master/index.js#L23) references `process.env.SCOPES` (plural).

Line 33 of [README.md](https://github.com/UWIT-IAM/oidc-client-nodejs/blob/master/README.md) describes a `SCOPE` (singular) environment variable.

Presumably these should match.

**Comment by Nogbit** [comment]
Thanks, good catch.  I'm changing it so these will come from Secrets Manager instead along with a new readme, hope to publish soon and will resolve this then.

**Comment by Nogbit** [comment]
Closing this now, what was just pushed to master is a working example using the serverless framework with a more secure implementation of secrets.

Next I'll move this into sub dirs of this repo and have more examples, not all of which will have code but will have some documentation/guides.
